apiVersion: v2
name: vault-domain-local
description: domain-local-specific HashiCorp Vault chart
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: vault
    version: "0.23.0"
    repository: https://helm.releases.hashicorp.com
