apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "externaldns.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "externaldns.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "externaldns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "externaldns.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "externaldns.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "quay.io/oriedge/k8s_gateway"
          imagePullPolicy: IfNotPresent
          args: ["-conf", "/etc/coredns/Corefile"]
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "externaldns.fullname" . }}
            items:
            - key: Corefile
              path: Corefile
            - key: db.{{ .Values.domainName }}
              path: db.{{ .Values.domainName }}
