apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "externaldns.serviceAccountName" . }}
  labels:
    {{- include "externaldns.labels" . | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
