apiVersion: v1
kind: Service
metadata:
  name: {{ include "externaldns.fullname" . }}
  labels:
    {{- include "externaldns.labels" . | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
  selector:
    {{- include "externaldns.selectorLabels" . | nindent 4 }}
