apiVersion: v2
name: cert-manager-domain-local
description: domain-local-specific cert-manager chart
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: cert-manager
    version: "v1.11.0"
    repository: https://charts.jetstack.io
